// Auto-generated neighborhood mappings from ViaParagem data
// Generated: 2026-05-04T22:34:54.959Z
// Total stops: 357 connected to routes

export const neighborhoodMappings = {
  Maputo: {
    'Baixa / Central': [
      'Aeroporto',
      'Albasine',
      'Albasine (Rotunda)',
      'Albazine (401)',
      'Albazine (402)',
      'Albazine (X04)',
      'Albazine (X07)',
      'Albazine (X08)',
      'Albazine (X09)',
      'Albazine (X10)',
      'Albazine (X40)',
      'Albazine (X41)',
      'Albert Lithule',
      'Albineiro',
      'Albineiro',
      'Alto Maé',
      'Anfrena',
      'Av. 25 de Setembro',
      'Av. de Moçambique',
      'Av. Eduardo Mondlane',
      'Av. Julius Nyerere',
      'Bananeiras',
      'Bananeiras',
      'Bananeiras',
      'Banco',
      'Banco',
      'Barraca Verde',
      'Barraca Verde',
      'Bombas',
      'Bombas',
      'Bombas da Machava',
      'Boquisso',
      'Campo',
      'Campo',
      'Canhueiro',
      'Canhueiro',
      'Canhueiro',
      'Canhueiro',
      'Canhueiro-P1499',
      'Canhueiro-P1499',
      'Carcaça',
      'Carcaça',
      'Carpintaria',
      'Casa Branca',
      'Casa Branca',
      'Casa Branca',
      'Cavalo Branco',
      'Cavalo Branco',
      'Cemitério',
      'Cemitério',
      'Centro',
      'Centro',
      'Centro',
      'Centro',
      'Centro de Saúde',
      'Centro de Saúde',
      'Chamissava',
      'Chapa Branca',
      'Chapa Branca',
      'Chiwewe',
      'Cimento',
      'Cimento',
      'Colete',
      'Contentor Vermelho',
      'Costa do Sol',
      'Distrito',
      'Distrito',
      'Distrito',
      'Distrito',
      'Dom Alexandre',
      'Escola',
      'Escola',
      'Esplanada',
      'Esplanada',
      'Estádio',
      'Estádio',
      'Estádio',
      'Estaleiro',
      'Estaleiro Naife',
      'Estaleiro Naife',
      'Facebook',
      'Ferragem',
      'Ginásio',
      'Grande Maputo',
      'Grande Maputo',
      'Hospital',
      'Hulene',
      'Hulene (Praça)',
      'Igreja Mundial',
      'Intena',
      'Intena',
      'Jardim',
      'Laurentina',
      'Machava Naz Naz',
      'Machava Naz Naz',
      'Machava Sede',
      'Machava Sede',
      'Machava Sede',
      'Magoanine',
      'Magoanine A',
      'Magoanine B',
      'Manduca',
      'Manduca',
      'Maquele',
      'Maquele',
      'Matchekane',
      'Matendene',
      'Maxaquene',
      'Michafutene',
      'Museu',
      'Mussumbuluco',
      'Nice Nice',
      'Padaria',
      'Padaria',
      'Padaria',
      'Padaria',
      'Padaria',
      'Padaria',
      'Padaria-P1494',
      'Padaria-P1494',
      'Paragem das Bombas (N4)',
      'Paragem Praia',
      'Pepsi',
      'Petromoc',
      'Petromoc',
      'Polana Cimento',
      'Polana Shopping',
      'Portagem',
      'Portagem (Matola)',
      'Praça dos Trabalhadores',
      'Praça dos Trabalhadores (Baixa)',
      'Pt',
      'Pt',
      'PT',
      'Rádio Marcone',
      'Recheio',
      'Rua da Escolinha',
      'Rua da Ferragem',
      'Rua da Igreja',
      'Rua da Padaria',
      'Rua do Parque',
      'Rua do Parque',
      'Serralharia',
      'Sial',
      'Sial',
      'Sommerschield',
      'Stop 12565544210',
      'T3 (Terminal)',
      'T3 Mercado',
      'Tamega',
      'Tamega',
      'Terminal Katembe',
      'Terminal Museu',
      'Terminal Zimpeto',
      'Xikhelene',
      'Xikhelene',
      'Xipamanine',
      'Zimpeto',
      'Zuide',
      'Zuide',
    ],
    'Zimpeto': [
      'Cruzamento de Zimpeto',
      'Cruzamento de Zimpeto',
    ],
    'Jardim': [
      'Jardim da Machava',
      'Jardim da Machava',
    ],
  },
  Matola: {
    'Matola Sede': [
      '006',
      '006',
      '007',
      '007',
      '120',
      '120',
      '16',
      '16',
      'Barraca Amarela',
      'Barraca Amarela',
      'Barraca Amarela Mcel',
      'Barraca Amarela Mcel',
      'Bic',
      'Boane',
      'Boane (101)',
      'Boane (103)',
      'Boane (104)',
      'Boane (105)',
      'Boane (106)',
      'Boane (707)',
      'Boane (C3)',
      'Bombas',
      'Bombas',
      'Casa Abandonada',
      'Casa Abandonada',
      'Casa Bonita',
      'Casa Bonita',
      'Ceres',
      'Ceres',
      'Chissano',
      'Chissano',
      'Chiwewe',
      'Cidade da Matola (109)',
      'Cidade da Matola (110)',
      'Cidade da Matola (C4)',
      'Contentor Amarelo',
      'Contentor Amarelo',
      'Control',
      'Controle',
      'Cossa',
      'Cossa',
      'Cruzamento',
      'Cruzamento',
      'Cruzamento de Namaacha',
      'Cruzamento de Namaacha',
      'Darling',
      'Darling',
      'EDM',
      'EDM',
      'Electro Matola',
      'Electro Matola',
      'Escola da Matola A',
      'Escola da Matola A',
      'Estaleiro',
      'Estaleiro',
      'Farmácia',
      'Farmácia',
      'Ferragem',
      'Ferragem',
      'Fim do Muro 2',
      'Fim do Muro 2',
      'Fim do Murro',
      'Finanças',
      'Finanças',
      'Fipag',
      'Fipag',
      'Godinho',
      'Godinho (Cruzamento)',
      'Hospital',
      'Hospital',
      'Ibavet',
      'Ibavet',
      'Igreja',
      'Igreja',
      'Igreja',
      'Igreja',
      'Igreja',
      'Igreja',
      'Inav',
      'João Mateus',
      'João Mateus',
      'João Mateus',
      'Kaino',
      'Kaino',
      'km 15',
      'km 15',
      'km 15',
      'km 15',
      'Lusalite',
      'Lusalite',
      'Macuacua',
      'Macuacua',
      'Mafuiane',
      'Mafureira',
      'Mafureira',
      'Mafurreira',
      'Mafurreira',
      'Magaiza',
      'Magaiza',
      'Malhampsene',
      'Malhampsene (105)',
      'Malhapsene',
      'Malhapsene',
      'Mangueira',
      'Mangueira',
      'Marliza',
      'Marliza',
      'Matola gare',
      'Matola Gare',
      'Matola Gare (207)',
      'Matola Gare (208)',
      'Matola Gare (C2)',
      'Matola Gare (Estação)',
      'Matola Rio',
      'Matola Rio',
      'Matola Rio',
      'Mercadinho',
      'Mercadinho',
      'Mercado Santos',
      'Mercado Santos',
      'Mesquita',
      'Mesquita',
      'Oficina',
      'Oficina',
      'Paragem 16',
      'Paragem 16',
      'Paragem 18',
      'Paragem 18',
      'Paragem da Shoprite (Matola)',
      'Paragem João Mateus',
      'Pilivi / Cmc',
      'Pilivi / Cmc',
      'Ponte',
      'Ponte',
      'Pontinha',
      'Pontinha',
      'Primeira Rua',
      'Primeira Rua',
      'Recheio',
      'Recheio',
      'Registro',
      'Registro',
      'Rua da Escola',
      'Rua da Escola',
      'Rua Real',
      'Rua Real',
      'Salão',
      'Salão',
      'Saul',
      'Saul',
      'Seta',
      'Seta',
      'Shoprite',
      'Sikwama (211)',
      'Sikwama (212)',
      'Sons de África',
      'Sons de África',
      'Takis',
      'Takis',
      'Tchumene',
      'Terminal de Malhampsene',
      'Terminal Matola Sede',
      'Terminal Matola Sede (Hanhane)',
      'Thandavanto',
      'Thandavanto',
      'Tribunal',
      'Tribunal',
      'Tricamo',
      'Tricamo',
      'União',
      'União',
    ],
    'Machava': [
      'Barraquinha',
      'Barraquinha',
      'Chapas',
      'Chapas',
      'Fibra Glass',
      'Fibra Glass',
      'Fomento (Paragem)',
      'Liberdade',
      'Liberdade',
      'Liberdade (Paragem)',
      'Machava Socimol',
      'Mercadinho',
      'Mercadinho',
      'Raimundo',
      'Raimundo',
      'Stop 12565371040',
      'Stop 12565371041',
    ],
    'Liberdade': [
      'Bic',
    ],
    'Fomento': [
      'Contentor Branco',
      'Oficina',
    ],
    'Matola Gare': [
      'Matola Gare',
      'Matola Gare',
    ],
  }
};

// Helper function to get stops by neighborhood
export function getStopsByNeighborhood(neighborhood: string, region: string): string[] {
  const mappings = neighborhoodMappings[region as 'Maputo' | 'Matola'];
  return mappings?.[neighborhood] || [];
}

// Helper function to get all neighborhoods by region
export function getNeighborhoodsByRegion(region: string): string[] {
  const mappings = neighborhoodMappings[region as 'Maputo' | 'Matola'];
  return Object.keys(mappings || {});
}
